"""Tests for the S5 virtual-base estimator's geometric core.

The headline claim these lock in is a negative one: the reachable-workspace
condition does **not** identify the robot base from demonstration trajectories.
That is a measured property of this capture, and it is what makes the estimator a
conditioning heuristic rather than a calibration method. If a future change made
the feasible set small, the estimator's whole framing would need revisiting --
hence the explicit test.
"""

import importlib.util
import pathlib

import numpy as np
import pytest

from opendm.data import se3
from opendm.kinematics import piper


def _load_script(name: str):
    root = pathlib.Path(__file__).resolve().parents[1]
    path = root / "script" / f"{name}.py"
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


estimator = _load_script("piper_estimate_root")
converter = _load_script("piper_ik_to_joints")


@pytest.fixture(scope="module")
def workspace():
    # Smaller than the default sample count; enough to shape the region.
    return estimator.build_workspace_mask(num_samples=120_000)


@pytest.fixture(scope="module")
def reachable_positions() -> np.ndarray:
    """Flange positions from random valid configurations, in the base frame."""
    rng = np.random.default_rng(3)
    lower, upper = piper.PIPER_JOINT_LIMITS.T
    joints = rng.uniform(lower, upper, (4000, piper.NUM_JOINTS))
    return piper.fk(joints)[:, :3, 3]


def test_workspace_mask_covers_the_arm_reach(workspace) -> None:
    mask, radius_edges, height_edges = workspace
    assert mask.any()
    # Piper's links sum to well under a metre of reach.
    assert radius_edges[-1] < 1.0
    assert height_edges[-1] < 1.0


def test_true_base_is_feasible(workspace, reachable_positions: np.ndarray) -> None:
    """Positions generated by FK must be reachable from the origin they came from."""
    assert estimator.unreachable_fraction(
        reachable_positions, np.zeros(3), workspace
    ) == pytest.approx(0.0, abs=1e-3)


def test_distant_base_is_infeasible(workspace, reachable_positions: np.ndarray) -> None:
    far = np.array([0.0, 0.0, 3.0])
    assert estimator.unreachable_fraction(reachable_positions, far, workspace) > 0.9


def test_workspace_condition_is_yaw_invariant(
    workspace, reachable_positions: np.ndarray
) -> None:
    """Joint 1 spins about the base z axis, so yaw cannot affect reachability.

    This is what reduces the base search from six parameters to four.
    """
    baseline = estimator.unreachable_fraction(
        reachable_positions, np.zeros(3), workspace
    )
    for yaw in (0.3, 1.1, -2.4):
        rotated = (
            se3.rotvec_to_mat(np.array([0.0, 0.0, yaw])) @ reachable_positions.T
        ).T
        assert estimator.unreachable_fraction(
            rotated, np.zeros(3), workspace
        ) == pytest.approx(baseline, abs=1e-3)


def test_reachability_alone_does_not_identify_the_base(
    workspace, reachable_positions: np.ndarray
) -> None:
    """The measured finding behind the estimator's design.

    A trajectory confined to part of the workspace admits many feasible bases.
    Here a compact cluster of poses is used, mimicking a demonstration, and the
    number of exactly-feasible base offsets is required to be large -- if it were
    small, reachability would be an estimator and the script should say so.
    """
    # A compact cluster, like a single manipulation task occupies.
    cluster = reachable_positions[
        np.linalg.norm(reachable_positions - reachable_positions.mean(0), axis=1) < 0.12
    ]
    assert len(cluster) > 50, "fixture did not produce a cluster"

    axis = np.arange(-0.2, 0.21, 0.05)
    feasible = sum(
        estimator.unreachable_fraction(
            cluster, cluster.mean(axis=0) + np.array([dx, dy, dz]), workspace
        )
        == 0.0
        for dx in axis
        for dy in axis
        for dz in axis
    )
    assert feasible > 20, (
        "reachability now pins the base down; the estimator is documented as a "
        "conditioning heuristic on the premise that it does not"
    )


def test_conditioning_cost_prefers_the_true_base_over_a_wild_one() -> None:
    """A base that makes the motion barely reachable must score worse than the truth."""
    rng = np.random.default_rng(11)
    lower, upper = piper.PIPER_JOINT_LIMITS.T
    start = rng.uniform(lower * 0.3, upper * 0.3, piper.NUM_JOINTS)
    joints = start + np.cumsum(rng.normal(scale=0.01, size=(40, piper.NUM_JOINTS)), 0)
    segment = piper.fk(np.clip(joints, lower, upper))

    truthful = estimator.conditioning_cost([segment], np.zeros(3), 0.0)
    stretched = estimator.conditioning_cost([segment], np.array([0.0, 0.0, -0.6]), 0.0)

    assert truthful["unreached_frac"] < 1e-6
    assert truthful["cost"] < stretched["cost"]


def test_conditioning_cost_reports_all_gate_metrics() -> None:
    """The report is the S5 go/no-go gate, so its keys are part of the contract."""
    joints = np.tile(piper.neutral_joints(), (20, 1))
    terms = estimator.conditioning_cost([piper.fk(joints)], np.zeros(3), 0.0)
    for key in (
        "pos_err_m",
        "unreached_frac",
        "pinned_frac",
        "near_singular_frac",
        "mean_step_rad",
        "branch_jump_frac",
        "cost",
    ):
        assert key in terms


def test_base_transform_roundtrip() -> None:
    """The converter must interpret the estimator's record the same way it was written."""
    estimate = {"position": [0.1, -0.6, 0.05], "yaw_rad": 0.7}
    transform = converter.base_transform(estimate)
    assert np.allclose(transform[:3, 3], estimate["position"])
    assert np.allclose(transform[:3, :3], se3.rotvec_to_mat(np.array([0.0, 0.0, 0.7])))


def test_converter_target_matches_the_registered_dataset() -> None:
    """S5's output directory must be where its registration expects to read from."""
    from opendm.dataset.piper_dual import held_out_dir

    assert converter.TARGET_REPRESENTATION in held_out_dir(
        converter.TARGET_REPRESENTATION
    )
    from opendm.dataset.register import CONVERSATION_DATA

    assert converter.TARGET_REPRESENTATION in (
        CONVERSATION_DATA["piper_fold_s5"]["jsonl_dir"]
    )
